openapi: 3.0.0
info:
  title: API Pedidos AOS
  version: '1.0'
  description: "API de Pedidos para Arquitecturas Orientadas a Servicios desarrollada por:\nSantiago Caro, \nMiguel Angel Perez &\nIván Pulido"
servers:
  - url: '{schema}://{servername}:{port}'
    variables:
      schema:
        enum:
          - http
          - https
        default: http
      servername:
        default: localhost
      port:
        default: '80'
paths:
  /pedidos:
    get:
      summary: Obtener Pedidos
      tags:
        - pedidos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  pedidos:
                    type: array
                    uniqueItems: false
                    items:
                      $ref: '#/components/schemas/Pedido'
          headers: {}
        '404':
          description: Not Found
      operationId: get-pedido
      description: Retorna una Lista de pedidos completa
    post:
      summary: Crear nuevo Pedido
      operationId: post-pedidos
      responses:
        '200':
          description: OK
        '409':
          description: Conflict
      description: Añade un Pedido a la lista de Pedidos con sus respectivos Campos
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pedido:
                  $ref: '#/components/schemas/Pedido'
    options:
      summary: Opciones soportadas
      operationId: options-pedidos
      description: Provee una lista de los metodos HTTP soportados
      responses:
        '200':
          description: OK
          headers:
            Allow:
              schema:
                type: string
              description: Cabecera Allow en donde van las operacions
  '/pedidos/{idPedido}':
    parameters:
      - schema:
          type: string
        name: idPedido
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - pedidos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    $ref: '#/components/schemas/Pedido'
            application/xml:
              schema:
                type: object
                properties: {}
          headers: {}
        '400':
          description: idPedido no valido
        '404':
          description: Pedido no encontrado
      operationId: get-pedidos-id_pedido
      description: Obtiene la información de un producto existente
    put:
      summary: ''
      operationId: put-pedidos-id_pedido
      description: Actualiza el pedido identificado por id_pedido
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                '':
                  $ref: '#/components/schemas/Pedido'
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      parameters: []
      responses:
        '202':
          description: Accepted
    delete:
      summary: ''
      operationId: delete-pedidos-id_pedido
      responses:
        '200':
          description: OK
        '400':
          description: idPedido no valido
        '404':
          description: idPedido no encontrado
      description: Elimina un pedido existente
    options:
      summary: ''
      operationId: options-pedidos-idPedido
      responses:
        '200':
          description: OK
          headers:
            Allow:
              schema:
                type: string
              description: 'Lista de metodos HTTP soportados'
      description: Devuelve la lista de métodos soportados HTTP
components:
  schemas:
    Producto:
      title: Producto
      type: object
      properties:
        producto:
          type: object
          properties:
            idProducto:
              type: integer
              format: int64
              example: 123456789
              minimum: 1
            descripcion:
              type: string
            categoria:
              $ref: '#/components/schemas/Categoria'
            _links:
              type: object
              description: link relations
              properties:
                parent:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
                self:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
      x-examples: {}
    Categoria:
      title: Categoria
      type: object
      properties:
        categoria:
          type: object
          properties:
            idCategoria:
              type: integer
              format: int64
              example: 123456789
              minimum: 1
            descripcion:
              type: string
            _links:
              type: object
              description: link relations
              properties:
                parent:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
                self:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
    Pedido:
      title: Pedido
      type: object
      properties:
        pedido:
          type: object
          properties:
            idPedido:
              type: integer
              format: int64
              example: 111111111
              minimum: 1
            tipo:
              type: string
              description: indica si es pedido de compra o de venta
              enum:
                - compra
                - venta
            producto:
              $ref: '#/components/schemas/Producto'
            cantidad:
              type: integer
              format: int32
              example: 23
              minimum: 1
            fechaCompra:
              type: string
              format: date-time
            estado:
              type: string
              description: estado del pedido
              enum:
                - abierto
                - aceptado
                - enviado
                - recibido
            _links:
              type: object
              description: link relations
              properties:
                parent:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
                self:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
            organizacion:
              $ref: '#/components/schemas/Organizacion'
    Organizacion:
      title: Organización
      type: object
      properties:
        organizacion:
          type: object
          properties:
            idOrganizacion:
              type: integer
              format: int64
              example: 32165478
            nombre:
              type: string
            descripcion:
              type: string
            teléfono:
              type: string
            e-mail:
              type: string
              format: email
            direccionPostal:
              type: object
              description: Dirección postal
              properties:
                calle:
                  type: string
                localidad:
                  type: string
                provincia:
                  type: string
                codPostal:
                  type: string
                  example: '28031'
                país:
                  type: string
            _links:
              type: object
              description: link relations
              properties:
                parent:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
                self:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
    Evento:
      title: Evento
      type: object
      properties:
        evento:
          type: object
          properties:
            idEvento:
              type: integer
              format: int64
              example: 878923748
              minimum: 1
            origen:
              type: string
              example: PEDIDOS
            fecha:
              type: string
              format: date-time
            mensaje:
              type: string
            nivel:
              type: string
              enum:
                - info
                - warn
                - error
            _links:
              type: object
              description: link relations
              properties:
                parent:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
                self:
                  type: object
                  properties:
                    href:
                      type: string
                      format: url
